from pathlib import Path

VERSION = "0.1.0"
DEFAULT_CONFIG_PATH = Path("config/models.json")
DEFAULT_RUNS_DIR = Path("runs")
REQUIRED_REPO_FILES = ("DESIGN.md", "DECISIONS.md", "OPEN_QUESTIONS.md")
ALLOWED_PATCH_FILES = {"DESIGN.md", "DECISIONS.md", "OPEN_QUESTIONS.md"}
PROMPT_SIZE_WARNING_LIMIT = 100_000

EXIT_SUCCESS = 0
EXIT_RUNTIME_ERROR = 1
EXIT_CONSISTENCY_FAILURE = 2
EXIT_PROVIDER_FAILURE = 3
EXIT_INVALID_MODEL_OUTPUT = 4
EXIT_NO_VALID_PATCH_PROPOSALS = 5
EXIT_PATCH_VALIDATION_FAILED = 6
EXIT_NO_ACCEPTABLE_SELECTION = 7
EXIT_USER_CANCELED = 8
